# docker-compose.yml
version: '3.9'

services:
  tensorflow_app:
    container_name: c_tensorflow
    platform: linux/amd64
    build:
      context: ./App
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
  tensorflow_jupyter:
    container_name: c_tensorflow_jupyter
    build:
      context: ./JupyterNotebooks
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./JupyterNotebooks/notebooks:/home/jovyan/work/notebooks 
    user: "root"
    environment:
      - NB_UID=1000
      - NB_GID=100
  